name: Build

# set criteria
on: [pull_request]

jobs:
  Test:
    # select the OS
    runs-on: ubuntu-20.04
    steps:
      # use actions
      - uses: actions/checkout@v2

      - name: Print version
        run: node -v && npm -v

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test
