# The workflow to publish package
name: Production

# Controls when the workflow will run
on:
  release:
    types: [ created ]
    branches: [ main ]

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Use Node.js 20.x version"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: "Install dependencies and build"
        run: npm ci && npm run build

      - name: "Publish to NPM"
        run: |
          npm config set registry https://registry.npmjs.org
          npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: "Publish to GitHub"
        run: |
          npm config set registry https://npm.pkg.github.com
          npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
